name: Generate ASCII Artwork

on:
  push

jobs:
  ascii_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Ensure Shell Script is Executable
      run: chmod +x ./ascii-script.sh

    - name: Install Dependencies and Execute Shell Script
      run: ./ascii-script.sh
      shell: bash
